image: firedrop/awscli
definitions:
  services:
    docker:
      memory: 2048
  steps:
    # Lint step to check code correctness
    - step: &lint
        name: 'Linting'
        services:
          - docker
        script:
          - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/lint.sh | bash -s

    # Testing step will look for Dockerfile and try to run tests for project
    - step: &test
        name: 'Testing'
        services:
          - docker
        script:
          - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/test.sh | bash -s

    # Build if there has been an increase in the .version file that is
    # greater than previous tags.
    - step: &build
        name: 'Container Building, Versioning, Image Pushing'
        services:
          - docker
        script:
           - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/build.sh | bash -s 
    
    # Legacy develop builds
    - step: &develop-build
        name: 'Develop Build'
        services:
          - docker
        script: 
          - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/develop.sh | bash -s 

    - step: &container-build-only
        name: 'Container Build'
        services:
          - docker
        script:
          - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/container-build.sh | bash -s

    - step: &manual-push
        name: 'Manual Push'
        services:
          - docker
        script:
          - curl -s https://bitbucket.org/firedropAI/pipelines-scripts/raw/master/manual.sh | bash -s
pipelines:
  
  branches:
    master:
      - step: *build
  
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined, but only when pull-request is created
      - parallel: 
        - step: *container-build-only
